### ISSUE TITLE
Add OS-agnostic function to install packages

### ISSUE THREAD

**Issue by silvertenor** [fabric-testbed/fabrictestbed-extensions#155] opened 2023-04-20 04:37 UTC
It would be nice to have a function in which the user does not have to specify the package manager to install packages. For example, calling something similar to "node.install_packages([list of packages here])" and having fablib fill in the package manager (dnf, yum, apt, etc) for us. This is minor but could be a cool feature. Please let me know what you think and if it would be worthwhile to spend any time on it.

**Comment by hussamnasir** [comment] 2023-04-20 09:33
I am not sure this task is achievable. A similar issue already exists with the use of the ansible package module. The problem is the package names are different across distributions and flavors. Since we are not talking about some basic packages this may be a hard problem.

**Comment by silvertenor** [comment] 2023-04-20 12:56
That makes sense! Thanks for the quick response

**Comment by sajith** [comment] 2023-04-23 16:20
It would seem like a "meta package manager" would be nice to have, but it is not going to be worth the effort.

Like Hussam said, package naming conventions are different across distributions and sometimes across releases of the same distribution.  And then there's the fact that the same software suite is packaged differently across distributions.  LaTeX in Debian vs RedHat comes to mind, for example, but there must other packages too that are more consequential to experimenters.  I guess we will also need to think about reproducibility concerns.

@silvertenor Feel free to close this issue if you are not going to pursue this further. :-)

**Closed** 2023-04-24 00:28 UTC
Labels: enhancement
